---
AWSTemplateFormatVersion: '2010-09-09'
Description: A simple EC2 instance template
Parameters:
  EC2InstanceType:
    Description: instance type
    Type: String
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 
        Ref: InstanceTypeParameter
      ImageId: ami-0aa7d40eeae50c9a9 # Amazon Linux 2 LTS
      KeyName: Jenkins_new
      SecurityGroups:
        - !Ref EC2InstanceSecurityGroup
  EC2InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
